DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS announcements CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS service_suggestions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS face_verifications CASCADE;

DROP EXTENSION IF EXISTS "pg_trgm";
